### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by mblais** [cjnaz/xbsjsonedit#2]
Hi cjnaz,

I made a few improvements - I added unbuffered single-char input so you don't need to hit Return after making a selection (speeds up the review process), and also added an "All" option when deleting duplicates, so the app doesn't prompt for the rest of the list.

LMK if you want to use this, and where to put it.

**Comment by cjnaz** [comment]
Hi.  Sounds good.  Send me a pull request please.

**Comment by mblais** [comment]
I'm afraid I'm pretty new to git and github.
I tried to follow these instructions:
https://yangsu.github.io/pull-request-tutorial/
but this happened:

git push origin getch-improvements
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/cjnaz/xbsjsonedit.git/'

**Comment by cjnaz** [comment]
Check this out...  https://reflectoring.io/github-fork-and-pull/

The trick is to create your own copy of the project/repo and push up your local changes to your repo copy, and then request the pull to me.

**Comment by cjnaz** [comment]
And how's life in Hawaii currently?

**Comment by mblais** [comment]
LOL I haven't been in Hawaii since 2015.. I must have an out of date profile somewhere.

Issue du jour (using MS Code):
```
> git push origin master:master
Logon failed, use ctrl+c to cancel basic credential prompt.
git: 'credential-cache' is not a git command. See 'git --help'.
git: 'credential-cache' is not a git command. See 'git --help'.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/mblais/xbsjsonedit.git/'
```
Same problem when executing `git push origin master:master` from bash.
I tried both `mblais` and my email as username, and I know my password is correct. Not a firewall issue since I know `git` has access.

**Comment by cjnaz** [comment]
Just keying off your area code.  

That git push may be trying to reach my repo (not sure).  You can check what the what's pointing to what with `git remote -v`.
- Assuming that you've forked my repo and then cloned your repo using the `Clone or download` button on your repo page then your local git environment should be referring to your github repo as the `origin`.  
- If you've not created a branch for your edits then you are editing on your local `master` branch, and to push it up to github should be just `git push` (since the master branch already exists on your repo).  The command line git command should prompt you for your github login info.   
- If you've created a new local branch for your edits, and you want to push that branch up to github then do a `git push --set-upstream origin <local branch name>`.  
- Then you should be able to submit the pull request.

Fyi, I don't have any experience with git within VS Code.  Good luck with the learning curve.  :>

**Comment by mblais** [comment]
Ack, the dangers of posting to GitHub via email reply 😁

Looks like the auth issue was 2FA on my GitHub account. Got that solved.

Pull request coming shortly.

**Comment by cjnaz** [comment]
Hey Matt, update posted.  Notable tweaks on your contribution (thanks!):
- Added all mode for duplicate folder deletes as well, for consistency.
- Sorted delete candidate list by ID number, so that the lowest ID number is retained in all mode deletes.  A year ago I was getting wholesale duplications of my Chrome bookmark bar with new/higher ID numbers, so retaining the lowest ID number seems always the right answer.
- Enhanced the single character entry mechanism for valid input checking.
